// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ebokScript.Models
{
    public partial class Message
    {
        public string Name { get; set; }
        public string Message1 { get; set; }
        public int Id { get; set; }
    }
}